# Generated by Django 4.0.4 on 2022-05-17 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fh', '0003_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='hero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fh.hero'),
        ),
    ]
